### ISSUE TITLE
Error in phone numbers

### ISSUE THREAD

**Issue by lush0n3** [npwd-community/npwd_services#10]
First of all good afternoon, I am having the following problem with the application
All the contacts of the players who are in service, are the own number of the one who is using the phone.

Capturas:
![image](https://user-images.githubusercontent.com/87586904/197357585-da893990-bb24-43a3-8311-c9e9d49ea094.png)
![image](https://user-images.githubusercontent.com/87586904/197357645-e872f0ac-6eb4-423d-a643-13bdd82dac29.png)

**Comment by Gameadictive** [comment]
So i was having this problem too any fix?

**Comment by lamaisondudev** [comment]
Hello, still no solution to this problem? I have the same
